### ISSUE TITLE
Help with MetaEukTogff error

### ISSUE THREAD

**Issue by karegapauline** [Andy-B-123/LittleScripts#1]
Good day @Andy-B-123. 
I am trying to present my metaeuk results and came across your script. But I keep getting an error

Traceback (most recent call last):
  File "MetaEuk_to_gff.py", line 32, in <module>
    ic(output_filename)
NameError: name 'ic' is not defined

that I don't really know ho to fix. Could you kindly assist? I've attached a screenshot of the error as well

![Screenshot from 2022-04-12 13-06-33](https://user-images.githubusercontent.com/27417671/162937935-ae4eb356-7709-4d68-9beb-8c95166bc922.png)

**Comment by Andy-B-123** [comment]
Hi, thank you for the issue! The problem here is that I missed a call to the 'icecream' library on line 32. I have commented this out in the latest version which should fix the error.
I would really recommend running the latest version of metaeuk! They include gff output now by default, it is more consistent than my script here :-) Let me know if I can help any further!
